POST http://localhost:8080/articles HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "id": "c7e95c46-feab-421e-8af7-a47bae261aa7",
  "title": "rock your body",
  "content": "come on come one rock your body"
}

### Listing all articles

GET http://localhost:8080/articles HTTP/1.1
Host: locahost:8080
Accept: application/json

### Get article by id
GET http://localhost:8080/articles/54168145-689b-4b18-86c6-dc32ce34a032 HTTP/1.1
Host: localhost:8080
Accept: application/json