POST http://localhost:8080/articles HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "id": "c7e95c46-feab-421e-8af7-a47bae261aa7",
  "title": "Oh my God",
  "content": "will i am??"
}

### Listing all articles

GET http://localhost:8080/articles HTTP/1.1
Host: locahost:8080
Accept: application/json